model$simulators$tmb(
  time_steps = values$time.steps,
  state = values$state,
  flow = c(
    infection_y = NA,
    progression_y = values$params[["progression_y"]],
    hospitalization_y = values$params[["hospitalization_y"]],
    discharge_y = values$params[["discharge_y"]],
    recovery_y = values$params[["recovery_y"]],
    deathH_y = values$params[["deathH_y"]],
    deathI_y = values$params[["deathI_y"]],
    infection_o = NA,
    progression_o = values$params[["progression_o"]],
    hospitalization_o = values$params[["hospitalization_o"]],
    discharge_o = values$params[["discharge_o"]],
    recovery_o = values$params[["recovery_o"]],
    deathH_o = values$params[["deathH_o"]],
    deathI_o = values$params[["deathI_o"]]),
  transmission_y = values$params[["transmission_y"]],
  transmission_o = values$params[["transmission_o"]],
  c_yy = values$params[["c_yy"]],
  c_yo = values$params[["c_yo"]],
  c_oy = values$params[["c_oy"]],
  c_oo = values$params[["c_oo"]],
  N_y = macpan2::empty_matrix,
  N_o = macpan2::empty_matrix,
  .mats_to_return = c("state", "total_inflow"),
  .dimnames = list(total_inflow = list(names(values$state), ""))
)
